Arreglos en la validación de los teléfonos
ISPP-2023-NGO-P3/frontend-aiding pull request #98
Opened 2023-04-27 15:21 UTC by rosmolarr

2023-04-27 17:24 UTC, mansanrod4 requested changes
- Al editar un socio: no se admiten los caracteres con acentos en los campos nombre, apellidos y titular de cuenta. 
- Hay números fijos que empiezan por 8 😅

2023-04-30 13:36 UTC, cardelbec approved these changes
No he encontrado nada más aparte del comentario que ha puesto manu

2023-05-06 13:38 UTC, rubsuadav commented
Solucionados bugs de bosco, necesaria revisión para que @Josdelsan haga merge de develop para desplegar

2023-05-06 16:09 UTC, mansanrod4 approved these changes

2023-05-06 17:27 UTC, mansanrod4 requested changes

2023-05-06 17:27 UTC, mansanrod4 commented on src/pages/information/map/CreateResource.js
falta validar que cuando es un número sea positivo, como en eventos.

2023-05-06 17:27 UTC, mansanrod4 commented on src/pages/information/map/UpdateResource.js
Igual que en el create

2023-05-06 17:32 UTC, rubsuadav commented on src/pages/information/map/CreateResource.js
ups, borre sin querer lo del positivo

2023-05-06 17:44 UTC, rubsuadav commented on src/pages/information/map/CreateResource.js
solucionado

2023-05-06 17:44 UTC, rubsuadav commented on src/pages/information/map/UpdateResource.js
también solucionado

2023-05-06 17:53 UTC, mansanrod4 approved these changes

2023-05-06 17:53 UTC, mansanrod4 approved these changes

2023-05-07 10:52 UTC, mansanrod4 approved these changes

2023-05-07 10:53 UTC, merged